baseURL = "http://michelle4sachse.com/"
languageCode = "en-us"
title = "Michelle For Sachse"
theme = "michelle-initio"
publishDir = "docs"



[params]
    name = "Michelle Howarth"
    description = "A mystery person"
    email = "anthony.russel42@example.com"
    phone = "+234 23 9873237"
    slogan = "A New Voice for Sachse"
    address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2018
    background = ""
    favicon = "images/favicon.ico"
    DateForm = "January 2, 2006"
    staticDir = ["static"]

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 3

[[menu.main]]
    name = "Meet Michelle"
    url = "/meet/"
    weight = 4
[[menu.main]]
    name = "get involved"
    url = "/involved/"
    weight = 5
[[menu.main]]
    name = "donate"
    url = "/donate/"
    weight = 7


[[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-115813132-1"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/michelle4sachse"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/michelle4sachse"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/michelle4sachse"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
